#!/usr/bin/env python3
"""Writes Sources/Tabs/About/AppConfig.generated.swift from ../app.config.ts.

app.config.ts holds the values that decide where someone's money goes (the About
window's Stripe payment links and receiving addresses). Agents may not edit it,
and a wrong value is invisible: it renders perfectly and pays a stranger. So the
native app never has them typed by hand. This script copies the exact strings out
of that one file, and AboutContentTests compares the generated Swift with
app.config.ts itself, so the two cannot differ unnoticed.

    Scripts/sync-app-config.py            rewrite the generated file
    Scripts/sync-app-config.py --check    exit 1 if the file is not what this would write

`make lint` runs the check. The parse is deliberately narrow: it accepts only the
file's current shape (two blocks of `key: 'string'` entries) and fails loudly on
anything else rather than guessing.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT.parent / "app.config.ts"
OUTPUT = ROOT / "Sources/Tabs/About/AppConfig.generated.swift"

# (app.config.ts block, Swift enum name)
BLOCKS = [("paymentLinks", "PaymentLinks"), ("cryptoAddresses", "CryptoAddresses")]
ENTRY = re.compile(r"^\s*([A-Za-z][A-Za-z0-9]*)\s*:\s*'([^'\\\n]*)'\s*,?\s*$")


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"(?m)^\s*//.*$", "", text)


def parse(text: str) -> dict[str, list[tuple[str, str]]]:
    text = strip_comments(text)
    found: dict[str, list[tuple[str, str]]] = {}
    for block, _ in BLOCKS:
        match = re.search(rf"\b{block}\s*:\s*\{{(.*?)\}}", text, flags=re.S)
        if not match:
            sys.exit(f"sync-app-config: no `{block}` block in {SOURCE}")
        entries = []
        for line in match.group(1).splitlines():
            if not line.strip():
                continue
            entry = ENTRY.match(line)
            if not entry:
                sys.exit(f"sync-app-config: unexpected line in `{block}`: {line.strip()!r}")
            entries.append((entry.group(1), entry.group(2)))
        if not entries:
            sys.exit(f"sync-app-config: `{block}` is empty")
        names = [name for name, _ in entries]
        if len(set(names)) != len(names):
            sys.exit(f"sync-app-config: `{block}` names a key twice")
        found[block] = entries
    return found


def render(found: dict[str, list[tuple[str, str]]]) -> str:
    lines = [
        "// GENERATED by Scripts/sync-app-config.py from ../app.config.ts. Do not edit.",
        "//",
        "// These values decide where someone's money goes. They are copied, never typed,",
        "// and AboutContentTests compares them with app.config.ts itself.",
        "",
        "enum AppConfig {",
    ]
    for index, (block, member) in enumerate(BLOCKS):
        if index:
            lines.append("")
        # One constant per key, as app.config.ts has them: a key the About window reads by
        # name and this file no longer has is a compile error, not a link that goes nowhere.
        lines.append(f"    enum {member} {{")
        for name, value in found[block]:
            lines.append(f'        static let {name} = "{value}"')
        lines.append("")
        lines.append("        /// Every entry by its key, for the tests.")
        lines.append("        static let all: [String: String] = [")
        for name, _ in found[block]:
            lines.append(f'            "{name}": {name},')
        lines.append("        ]")
        lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    if not SOURCE.is_file():
        sys.exit(f"sync-app-config: {SOURCE} not found")
    expected = render(parse(SOURCE.read_text()))
    if "--check" in sys.argv[1:]:
        if not OUTPUT.is_file() or OUTPUT.read_text() != expected:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date with app.config.ts: run Scripts/sync-app-config.py")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
