#!/bin/bash
# Prints build/Version.xcconfig: the root package.json's "version", verbatim, as
# both MARKETING_VERSION (CFBundleShortVersionString) and CURRENT_PROJECT_VERSION
# (CFBundleVersion). That string is the Electron app's version too (its About,
# TERM_PROGRAM_VERSION and Info.plist), so the two apps of one commit report the
# same version everywhere.
#
#   Scripts/version-xcconfig.sh > build/Version.xcconfig     (`make project` does)
set -euo pipefail

package="$(cd "$(dirname "$0")/../.." && pwd)/package.json"
version="$(plutil -extract version raw -o - "$package")"
[ -n "$version" ] || { echo "version-xcconfig: no version in $package" >&2; exit 1; }

echo "// Generated by Scripts/version-xcconfig.sh from package.json. Do not edit."
echo "MARKETING_VERSION = $version"
echo "CURRENT_PROJECT_VERSION = $version"
