// GENERATED by Scripts/sync-app-config.py from Config/AppConfig.plist. Do not edit.
//
// These values decide where someone's money goes. They are copied, never typed,
// and AboutContentTests compares them with Config/AppConfig.plist itself.

enum AppConfig {
    enum PaymentLinks {
        static let coffee = "https://donate.stripe.com/4gMeV67Jgb5XfgU6C31Jm02"
        static let beans = "https://donate.stripe.com/14A00c4x40rj8Sw0dF1Jm00"
        static let grinder = "https://donate.stripe.com/fZu3cobZw4HzfgUgcD1Jm01"

        /// Every entry by its key, for the tests.
        static let all: [String: String] = [
            "coffee": coffee,
            "beans": beans,
            "grinder": grinder,
        ]
    }

    enum CryptoAddresses {
        static let btc = "bc1qfj8yps3equmypd6kzlje8knxdhnw7pe8psqk50"
        static let eth = "0x022A23E510e6d5Cd5e2F2F7cEf6A1f19Da57Ac43"

        /// Every entry by its key, for the tests.
        static let all: [String: String] = [
            "btc": btc,
            "eth": eth,
        ]
    }
}
