#!/bin/bash
# Prints the XcodeGen include list of every plugin (Plugins/*/plugin.yml), for
# project.yml to include as build/plugins.yml. A plugin is a folder: adding one
# edits no shared file.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"
echo "# Generated by Scripts/plugin-includes.sh; don't edit."
echo "include:"
found=0
for spec in Plugins/*/plugin.yml; do
  [ -f "$spec" ] || continue
  printf '  - path: %s\n    relativePaths: false\n' "$spec"
  found=1
done
[ "$found" -eq 1 ] || echo "  []"
