#!/usr/bin/env python3
"""Writes Sources/Tabs/About/AppConfig.generated.swift from Config/AppConfig.plist.

Config/AppConfig.plist holds the values that decide where someone's money goes (the
About window's Stripe payment links and receiving addresses). Agents may not edit it,
and a wrong value is invisible: it renders perfectly and pays a stranger. So the app
never has them typed by hand. This script copies the exact strings out of that one
file, and AboutContentTests compares the generated Swift with the plist itself, so the
two cannot differ unnoticed.

    Scripts/sync-app-config.py            rewrite the generated file
    Scripts/sync-app-config.py --check    exit 1 if the file is not what this would write

`make lint` runs the check. The read is deliberately strict: it accepts only the file's
current shape (a `donations` dict holding the two blocks, each of `key: string`
entries) and fails loudly on anything else rather than guessing.
"""

import plistlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "Config/AppConfig.plist"
OUTPUT = ROOT / "Sources/Tabs/About/AppConfig.generated.swift"

# (plist block, Swift enum name)
BLOCKS = [("paymentLinks", "PaymentLinks"), ("cryptoAddresses", "CryptoAddresses")]
KEY = re.compile(r"[A-Za-z][A-Za-z0-9]*")
# Copied into a Swift string literal verbatim: nothing that would need escaping.
VALUE = re.compile(r"[^\"\\\n\r]+")


def parse(data: bytes) -> dict[str, list[tuple[str, str]]]:
    try:
        root = plistlib.loads(data)
    except Exception as error:
        sys.exit(f"sync-app-config: {SOURCE} is not a readable property list: {error}")
    if not isinstance(root, dict) or set(root) != {"donations"}:
        sys.exit(f"sync-app-config: {SOURCE} must hold exactly one dict, `donations`")
    donations = root["donations"]
    expected = {block for block, _ in BLOCKS}
    if not isinstance(donations, dict) or set(donations) != expected:
        sys.exit(f"sync-app-config: `donations` must hold exactly {sorted(expected)}")
    found: dict[str, list[tuple[str, str]]] = {}
    for block, _ in BLOCKS:
        entries = donations[block]
        if not isinstance(entries, dict) or not entries:
            sys.exit(f"sync-app-config: `{block}` must be a non-empty dict")
        for name, value in entries.items():
            if not KEY.fullmatch(name):
                sys.exit(f"sync-app-config: unexpected key in `{block}`: {name!r}")
            if not isinstance(value, str) or not VALUE.fullmatch(value):
                sys.exit(f"sync-app-config: `{block}.{name}` must be a one-line string")
        found[block] = list(entries.items())
    return found


def render(found: dict[str, list[tuple[str, str]]]) -> str:
    lines = [
        "// GENERATED by Scripts/sync-app-config.py from Config/AppConfig.plist. Do not edit.",
        "//",
        "// These values decide where someone's money goes. They are copied, never typed,",
        "// and AboutContentTests compares them with Config/AppConfig.plist itself.",
        "",
        "enum AppConfig {",
    ]
    for index, (block, member) in enumerate(BLOCKS):
        if index:
            lines.append("")
        # One constant per key, as the plist has them: a key the About window reads by
        # name and this file no longer has is a compile error, not a link that goes nowhere.
        lines.append(f"    enum {member} {{")
        for name, value in found[block]:
            lines.append(f'        static let {name} = "{value}"')
        lines.append("")
        lines.append("        /// Every entry by its key, for the tests.")
        lines.append("        static let all: [String: String] = [")
        for name, _ in found[block]:
            lines.append(f'            "{name}": {name},')
        lines.append("        ]")
        lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    if not SOURCE.is_file():
        sys.exit(f"sync-app-config: {SOURCE} not found")
    expected = render(parse(SOURCE.read_bytes()))
    if "--check" in sys.argv[1:]:
        if not OUTPUT.is_file() or OUTPUT.read_text() != expected:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date with {SOURCE.relative_to(ROOT)}: run Scripts/sync-app-config.py")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
